RecruitRW/RecruitRW/Models/RwModels/Candidate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RecruitRW.Models
{
    public class Candidate
    {
        public Candidate()
        {
            Contacts = new List<ContactInformation>();
            Skills = new List<Skill>();
        }
        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public DateTime RegistrationDate { get; set; }
        public DateTime? ConversationDate { get; set; }

        public virtual ICollection<ContactInformation> Contacts { get; set; }

        public virtual Adress Adress { get; set; }

        public virtual ICollection<Skill> Skills { get; set; }
    }
}

RecruitRW/RecruitRW/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RecruitRW.Models;

namespace RecruitRW.Controllers
{
    public class CandidatesController : Controller
    {
        private RecruitContext db = new RecruitContext();

        // GET: Candidates
        public ActionResult Index()
        {
           IEnumerable<Candidate> candidates = db.Candidates.Include(c => c.Adress).ToList();

            return View(candidates);
        }

        // GET: Candidates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            // ViewBag.Id = new SelectList(db.Adresses, "CandidateId", "City");
            Candidate candidate = new Candidate();
            candidate.Adress = new Adress();
            candidate.Skills = new List<Skill>();
            candidate.RegistrationDate = DateTime.UtcNow.Date;
            return View(candidate);
        }

        public PartialViewResult _GetSkills(Candidate candidate)
        {
            if (candidate.Skills == null)
                candidate.Skills = new List<Skill>();
            //List<Skill> skills = new List<Skill>();
            //skills.Add(new Skill { SkillName = "ASP", SkillValue = 10 });
            //if(Id!=0)
            //{
            //    List<Skill> skills1 = db.Candidates.Include("Skills").FirstOrDefault(item => item.Id == Id).Skills.ToList();
            //    if (skills1 != null)
            //        skills = skills1;
            //}
            return PartialView("_Skills", candidate.Skills);
        }

        public PartialViewResult _AddSkill(Skill s)
        {
           
            return PartialView("_SkillAdd", s);
        }

        public PartialViewResult _AddNewSkill(Candidate candidate, Skill s)
        {
            candidate.Skills.Add(s);

            return PartialView("_Skills", candidate.Skills);
           // return PartialView("_SkillAdd", s);
        }

        [ChildActionOnly()]
        public PartialViewResult _AdressPartial(Adress adress)
        {
            return PartialView("_Adress", adress);
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // public ActionResult Create([Bind(Include = "Id,FirstName,SecondName,RegistrationDate,ConversationDate,Adress")] Candidate candidate,Adress adress)
        public ActionResult Create(Candidate candidate,Adress adress,IEnumerable<Skill> skill)
        {
            if (ModelState.IsValid)
            {
                db.Candidates.Add(candidate);
                adress.Candidate = candidate;
                db.Adresses.Add(adress);
                if(skill!=null)
                    foreach(Skill sk in skill)
                    {
                        sk.Candidate = candidate;
                        db.Skills.Add(sk);
                    }
              //  skill.Candidate = candidate;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id = new SelectList(db.Adresses, "CandidateId", "City", candidate.Id);
            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
         //  Adress adress =  new Adress { City = "ZP" };
         //   adress.Candidate = candidate;

          //  db.Adresses.Add(adress);
           // db.SaveChanges();
            //candidate.Adress = 
            ViewBag.Id = new SelectList(db.Adresses, "CandidateId", "City", candidate.Id);
            return View(candidate);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,SecondName,RegistrationDate,ConversationDate")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Adresses, "CandidateId", "City", candidate.Id);
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidates.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidate candidate = db.Candidates.Find(id);
            db.Candidates.Remove(candidate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RecruitRW/RecruitRW/Views/Candidates/Create.cshtml
@model RecruitRW.Models.Candidate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@*@using (Html.BeginForm("Create","Candidates",FormMethod.Post)) 
{*@
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Candidate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConversationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConversationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConversationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Adress.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress.Street, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div style="background-color:blue">
            @Html.Action("_AdressPartial", "Candidates", new { adress = @Model.Adress });
        </div>

        <div style="background-color:orange">
            @Html.Action("_GetSkills","Candidates",@Model);
        </div>
        @*<div style="background-color:green">
            @Html.Partial("_Adress", Model.Adress);
        </div>*@
        <hr />
        @*<div style="background-color:green">
            @Html.Partial("_Skills", Model.Skills);
        </div>*@


        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>*@
@*}*@

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RecruitRW/RecruitRW/Views/Candidates/Delete.cshtml
@model RecruitRW.Models.Candidate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adress.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConversationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConversationDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RecruitRW/RecruitRW/Views/Candidates/Details.cshtml
@model RecruitRW.Models.Candidate

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adress.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConversationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConversationDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RecruitRW/RecruitRW/Views/Candidates/Edit.cshtml
@model RecruitRW.Models.Candidate

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Candidate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConversationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConversationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConversationDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" >
            @Html.Partial("_Adress", Model.Adress);
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RecruitRW/RecruitRW/Views/Candidates/Index.cshtml
@model IEnumerable<RecruitRW.Models.Candidate>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adress.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConversationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Adress.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SecondName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConversationDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>